### ISSUE TITLE
大佬，这个问题怎么解决

### ISSUE THREAD

**Issue by frf123** [XinRoom/Bike-Distribution-Model#1]
AttributeError: 'AxesSubplot' object has no attribute 'hold'

**Comment by XinRoom** [comment]
[matplotlib](https://github.com/matplotlib/matplotlib/releases) 3.0.0+ 版本改变了相关api
你可以进行降级`pip install matplotlib==2.2.4`

或者你需要对照官方api进行升级: https://matplotlib.org/api/axes_api.html
