### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by FengXuas** [XinRoom/Bike-Distribution-Model#2]
你好，请问数据是怎么获取的呢

**Comment by XinRoom** [comment]
我当时是通过摩拜微信小程序的api 用python爬了3天3夜，不知道现在还行不行

据我了解，有部分人是通过渠道购买的数据，具体的我就不清楚了

**Comment by FengXuas** [comment]
你好，代码能分享下吗，我在爬ofo的数据，但是单车id都是6666了，作分析不是很好

**Comment by XinRoom** [comment]
抱歉，我的代码已经过时了，近期没有相关的涉猎，你可能需要多找找api了，并且看看相关api是否需要身份验证

**Comment by FengXuas** [comment]
好的，谢谢，不过感想大佬的这个程序，帮了不少忙
